name = "prunt_motion_planner"
description = "Motion planner for Prunt. Does not include motion executor."
version = "0.1.0-dev"

authors = ["Liam Powell"]
maintainers = ["Liam Powell <liam@liampll.com>"]
maintainers-logins = ["liampwll"]

[[depends-on]]
prunt_physical_types = "*"
[[pins]]
prunt_physical_types = { path = "../prunt_physical_types" }

[build-switches]
release.optimization = [
  "-O3",
  "-gnatn",
  "-fdata-sections",
  "-ffunction-sections",
  "-flto=auto",
  "-fuse-linker-plugin",
  "-fno-pie",
  "-fno-pic",
  "-ffat-lto-objects"
]
